### ISSUE TITLE
speech-dispatcher support

### ISSUE THREAD

**Issue by AlanGriffiths** [snapcrafters/scummvm#12]
Continuing digression started on #11 

> I tried to add what you suggested to the launch-script. Even in devmode, this is what I get:
> 
> ```
> ln: failed to create symbolic link '/run/user/0/snap.snapcraft/speech-dispatcher/speechd.sock': No such file or directory
> WARNING: Couldn't initialize text to speech through speech-dispatcher!
> ```
> 
> Both libspeechd2 and speech-dispatcher are added to the stage packages.

Your message is about `/run/user/0/...` i.e. root, not a "normal" user. Also, I would have expected `.../snap.scummvm/` when running the scummvm snap not `.../snap.snapcraft/` which would belong to the snapcraft snap.

I think I must have miscommunicated. I was assuming that `.../speech-dispatcher/speechd.sock` (if available) would be created as part of a user session, not within the snap. 

Could you clarify what you added where? Is there a branch?

**Comment by AlanGriffiths** [comment]
@lotharsm did you notice I replied here?

**Comment by lotharsm** [comment]
>Your message is about /run/user/0/... i.e. root, not a "normal" user. Also, I would have expected .../snap.scummvm/ when running the scummvm snap not .../snap.snapcraft/ which would belong to the snapcraft snap.

Yes, that's exactly what I don't understand (yet). From what I read, speech-dispatcher has to run as a service since it provides some sort of daemon (you can systemctl status speech-dispatcher on a "standard" system). And since it can't communicate with the host because it's looking in the wrong directory, it fails to connect to the socket. However, this doesn't explain why it's lookin in `/run/user/0/ ` and not `/run/user/$userid`.

My idea now was to "pack" the speech-dispatcher "daemon" into the snap itself, so that it spins up a speech-dispatcher instance when the snap is launched.

There's no branch yet - all I did so far was to add the libspeechd2 and speech-dispatcher packages to the staging packages and add the script magic you sent earlier to the alsa-launch script since this script already acts as a "wrapper" or launcher.

**Comment by AlanGriffiths** [comment]
The alsa-launcher script is created at build time by a script. You've added stuff so that $XDG_RUNTIME_DIR is evaluated at build time. Hence the "snap.snapcraft".
